query GitHubViewer {
  viewer {
    name
    login
    avatarUrl
    bioHTML
    repositories(first:100) {
      nodes {
        id
        name
        description
        isFork
        isPrivate
        isArchived
        updatedAt
        url
        parent {
          nameWithOwner
          url
        }
      }
    }
  }
}
