query($ghLogin: String!, $after: String) {
  user(login: $ghLogin) {
    id
    name
    login
    avatarUrl
    bioHTML
    repositories(
      first: 100
      after: $after
      affiliations: [OWNER, ORGANIZATION_MEMBER, COLLABORATOR]
      ownerAffiliations: [OWNER, ORGANIZATION_MEMBER, COLLABORATOR]
    ) {
      totalCount
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        id
        viewerCanAdminister
        name
        description
        isFork
        isPrivate
        isArchived
        updatedAt
        url
        parent {
          nameWithOwner
          url
        }
        owner {
          login
          url
        }
      }
    }
  }
}
