query GitHubViewer {
  viewer {
    name
    login
    avatarUrl
    bioHTML
    repositories(first:100) {
      totalCount
      nodes {
        name
        description
        isFork
        isPrivate
        isArchived
        updatedAt
        url
      }
    }
  }
}
